language: node_js
node_js:
  - 16.10.0
script:
  - "npm run build"

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: book-store-web-22
  on:
    all_branches: true
  